:- use_module( problem ).
:- use_module( actions ).
:- use_module( percept ).

call( check_local ).
call( adjust_safe ).
call( move(21,37) ).
call( check_local ).
call( adjust_safe ).
call( move(21,36) ).
call( check_local ).
call( mark_unsafe ).
call( move(20,37) ).
call( check_local ).
call( mark_unsafe ).
call( move(20,38) ).
call( check_local ).
call( adjust_safe ).
call( move(19,38) ).
call( check_local ).
call( mark_unsafe ).
call( move(22,37) ).
call( check_local ).
call( adjust_safe ).
call( move(22,36) ).
call( check_local ).
call( adjust_safe ).
call( move(23,36) ).
call( check_local ).
call( adjust_safe ).
call( move(23,37) ).
call( check_local ).
call( adjust_safe ).
call( move(23,38) ).
call( check_local ).
call( adjust_safe ).
call( move(22,38) ).
call( check_local ).
call( adjust_safe ).
call( move(22,39) ).
call( check_local ).
call( adjust_safe ).
call( move(21,39) ).
call( check_local ).
call( adjust_safe ).
call( move(20,39) ).
call( check_local ).
call( adjust_safe ).
call( move(19,39) ).
call( check_local ).
call( adjust_safe ).
call( move(18,39) ).
call( check_local ).
call( adjust_safe ).
call( move(17,39) ).
call( check_local ).
call( mark_unsafe ).
call( move(23,39) ).
call( check_local ).
call( adjust_safe ).
call( move(24,39) ).
call( assertz(at(heart,pos(24,39))) ).
call( check_local ).
call( adjust_safe ).
call( move(25,39) ).
call( check_local ).
call( adjust_safe ).
call( move(25,38) ).
call( check_local ).
call( adjust_safe ).
call( move(25,37) ).
call( check_local ).
call( adjust_safe ).
call( move(25,36) ).
call( check_local ).
call( mark_unsafe ).
call( move(26,39) ).
call( check_local ).
call( adjust_safe ).
call( move(27,39) ).
call( check_local ).
call( adjust_safe ).
call( move(27,38) ).
call( check_local ).
call( adjust_safe ).
call( move(27,37) ).
call( check_local ).
call( adjust_safe ).
call( move(27,36) ).
call( check_local ).
call( adjust_safe ).
call( move(27,35) ).
call( check_local ).
call( adjust_safe ).
call( move(27,34) ).
call( check_local ).
call( adjust_safe ).
call( move(28,34) ).
call( check_local ).
call( adjust_safe ).
call( move(29,34) ).
call( assertz(at(rupee,pos(29,34))) ).
call( pickup_item(rupee,29,34) ).
call( check_local ).
call( adjust_safe ).
call( move(30,34) ).
call( check_local ).
call( adjust_safe ).
call( move(31,34) ).
call( check_local ).
call( adjust_safe ).
call( move(32,34) ).
call( check_local ).
call( adjust_safe ).
call( move(33,34) ).
call( check_local ).
call( adjust_safe ).
call( move(33,33) ).
call( assertz(at(sword,pos(33,33))) ).
call( pickup_item(sword,33,33) ).
call( check_local ).
call( adjust_safe ).
call( move(33,32) ).
call( check_local ).
call( adjust_safe ).
call( move(33,31) ).
call( check_local ).
call( adjust_safe ).
call( move(33,30) ).
call( check_local ).
call( adjust_safe ).
call( move(34,30) ).
call( check_local ).
call( adjust_safe ).
call( move(35,30) ).
call( check_local ).
call( adjust_safe ).
call( move(35,29) ).
call( check_local ).
call( mark_unsafe ).
call( move(34,31) ).
call( check_local ).
call( adjust_safe ).
call( move(35,31) ).
call( check_local ).
call( adjust_safe ).
call( move(36,31) ).
call( check_local ).
call( adjust_safe ).
call( move(37,31) ).
call( check_local ).
call( adjust_safe ).
call( move(38,31) ).
call( check_local ).
call( mark_unsafe ).
call( move(27,40) ).
call( check_local ).
call( adjust_safe ).
call( move(27,41) ).
call( check_local ).
call( adjust_safe ).
call( move(26,41) ).
call( assertz(at(rupee,pos(26,41))) ).
call( pickup_item(rupee,26,41) ).
call( check_local ).
call( adjust_safe ).
call( move(25,41) ).
call( assertz(at(heart,pos(25,41))) ).
call( check_local ).
call( mark_unsafe ).
call( move(28,41) ).
call( check_local ).
call( adjust_safe ).
call( move(29,41) ).
call( check_local ).
call( adjust_safe ).
call( move(29,40) ).
call( check_local ).
call( adjust_safe ).
call( move(29,39) ).
call( check_local ).
call( mark_unsafe ).
call( move(30,41) ).
call( check_local ).
call( adjust_safe ).
call( move(31,41) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(32,41) ).
call( move(32,41) ).
call( check_local ).
call( adjust_safe ).
call( move(33,41) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(34,41) ).
call( move(34,41) ).
call( check_local ).
call( adjust_safe ).
call( move(21,36) ).
call( attack_monster(20,36) ).
call( move(20,36) ).
call( check_local ).
call( adjust_safe ).
call( move(19,36) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(19,37) ).
call( attack_monster(19,37) ).
call( move(19,37) ).
call( assertz(at(sword,pos(19,37))) ).
call( pickup_item(sword,19,37) ).
call( check_local ).
call( adjust_safe ).
call( move(17,39) ).
call( attack_monster(17,38) ).
call( move(17,38) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(17,37) ).
call( move(17,37) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(17,36) ).
call( move(17,36) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(16,36) ).
call( move(24,39) ).
call( pickup_item(heart,24,39) ).
call( move(16,36) ).
call( check_local ).
call( adjust_safe ).
call( move(16,35) ).
call( assertz(at(sword,pos(16,35))) ).
call( pickup_item(sword,16,35) ).
call( check_local ).
call( adjust_safe ).
call( move(16,34) ).
call( check_local ).
call( mark_unsafe ).
call( move(15,36) ).
call( check_local ).
call( adjust_safe ).
call( move(14,36) ).
call( check_local ).
call( adjust_safe ).
call( move(13,36) ).
call( check_local ).
call( adjust_safe ).
call( move(13,35) ).
call( check_local ).
call( adjust_safe ).
call( move(13,34) ).
call( check_local ).
call( mark_unsafe ).
call( move(12,36) ).
call( check_local ).
call( adjust_safe ).
call( move(11,36) ).
call( check_local ).
call( adjust_safe ).
call( move(10,36) ).
call( check_local ).
call( adjust_safe ).
call( move(9,36) ).
call( assertz(at(sword,pos(9,36))) ).
call( pickup_item(sword,9,36) ).
call( check_local ).
call( adjust_safe ).
call( move(8,36) ).
call( check_local ).
call( adjust_safe ).
call( move(7,36) ).
call( check_local ).
call( adjust_safe ).
call( move(6,36) ).
call( check_local ).
call( adjust_safe ).
call( move(5,36) ).
call( check_local ).
call( adjust_safe ).
call( move(4,36) ).
call( check_local ).
call( mark_unsafe ).
call( move(10,37) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(10,38) ).
call( move(10,38) ).
call( check_local ).
call( adjust_safe ).
call( move(10,39) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(10,40) ).
call( move(10,40) ).
call( check_local ).
call( adjust_safe ).
call( move(10,41) ).
call( assertz(at(rupee,pos(10,41))) ).
call( pickup_item(rupee,10,41) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(11,41) ).
call( move(11,41) ).
call( check_local ).
call( adjust_safe ).
call( move(12,41) ).
call( check_local ).
call( adjust_safe ).
call( move(12,40) ).
call( check_local ).
call( mark_unsafe ).
call( move(13,41) ).
call( check_local ).
call( adjust_safe ).
call( move(13,40) ).
call( check_local ).
call( adjust_safe ).
call( move(13,39) ).
call( check_local ).
call( mark_unsafe ).
call( move(14,41) ).
call( check_local ).
call( adjust_safe ).
call( move(15,41) ).
call( check_local ).
call( adjust_safe ).
call( move(15,40) ).
call( check_local ).
call( adjust_safe ).
call( move(15,39) ).
call( check_local ).
call( adjust_safe ).
call( move(15,38) ).
call( check_local ).
call( adjust_safe ).
call( move(16,41) ).
call( check_local ).
call( adjust_safe ).
call( move(17,41) ).
call( check_local ).
call( adjust_safe ).
call( move(18,41) ).
call( check_local ).
call( adjust_safe ).
call( move(19,41) ).
call( check_local ).
call( adjust_safe ).
call( move(20,41) ).
call( check_local ).
call( adjust_safe ).
call( move(21,41) ).
call( check_local ).
call( adjust_safe ).
call( move(22,41) ).
call( check_local ).
call( adjust_safe ).
call( move(23,41) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(24,41) ).
call( attack_monster(24,41) ).
call( move(25,41) ).
call( pickup_item(heart,25,41) ).
call( attack_monster(24,41) ).
call( move(24,41) ).
call( check_local ).
call( adjust_safe ).
call( move(25,36) ).
call( attack_monster(25,35) ).
call( move(25,35) ).
call( check_local ).
call( adjust_safe ).
call( move(25,34) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(24,34) ).
call( move(24,34) ).
call( assertz(at(sword,pos(24,34))) ).
call( pickup_item(sword,24,34) ).
call( assertz(at(heart,pos(24,34))) ).
call( pickup_item(heart,24,34) ).
call( assertz(at(rupee,pos(24,34))) ).
call( pickup_item(rupee,24,34) ).
call( check_local ).
call( adjust_safe ).
call( move(24,33) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(24,32) ).
call( move(24,32) ).
call( check_local ).
call( adjust_safe ).
call( move(25,32) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(26,32) ).
call( move(26,32) ).
call( check_local ).
call( adjust_safe ).
call( move(27,32) ).
call( assertz(at(rupee,pos(27,32))) ).
call( pickup_item(rupee,27,32) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(28,32) ).
call( move(28,32) ).
call( check_local ).
call( adjust_safe ).
call( move(28,31) ).
call( check_local ).
call( mark_unsafe ).
call( move(29,32) ).
call( assertz(at(rupee,pos(29,32))) ).
call( pickup_item(rupee,29,32) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(30,32) ).
call( move(30,32) ).
call( check_local ).
call( adjust_safe ).
call( move(31,32) ).
call( assertz(at(rupee,pos(31,32))) ).
call( pickup_item(rupee,31,32) ).
call( check_local ).
call( adjust_safe ).
call( move(38,31) ).
call( attack_monster(39,31) ).
call( move(39,31) ).
call( check_local ).
call( adjust_safe ).
call( move(40,31) ).
call( check_local ).
call( mark_unsafe ).
call( move(39,32) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(39,33) ).
call( move(39,33) ).
call( check_local ).
call( adjust_safe ).
call( move(38,33) ).
call( check_local ).
call( adjust_safe ).
call( move(37,33) ).
call( check_local ).
call( adjust_safe ).
call( move(36,33) ).
call( assertz(at(sword,pos(36,33))) ).
call( pickup_item(sword,36,33) ).
call( check_local ).
call( adjust_safe ).
call( move(35,33) ).
call( check_local ).
call( adjust_safe ).
call( move(35,34) ).
call( check_local ).
call( adjust_safe ).
call( move(36,34) ).
call( check_local ).
call( adjust_safe ).
call( move(36,35) ).
call( check_local ).
call( mark_unsafe ).
call( move(35,35) ).
call( check_local ).
call( adjust_safe ).
call( move(35,36) ).
call( check_local ).
call( mark_unsafe ).
call( move(38,34) ).
call( check_local ).
call( adjust_safe ).
call( move(39,34) ).
call( check_local ).
call( adjust_safe ).
call( move(39,35) ).
call( check_local ).
call( adjust_safe ).
call( move(38,35) ).
call( check_local ).
call( adjust_safe ).
call( move(38,36) ).
call( check_local ).
call( adjust_safe ).
call( move(39,36) ).
call( check_local ).
call( adjust_safe ).
call( move(39,37) ).
call( check_local ).
call( adjust_safe ).
call( move(38,37) ).
call( check_local ).
call( mark_unsafe ).
call( attack_monster(37,37) ).
call( move(37,37) ).
call( check_local ).
call( adjust_safe ).
call( move(36,37) ).
call( check_local ).
call( mark_unsafe ).
call( move(4,36) ).
